FROM cgr.dev/chainguard/wolfi-base:latest@sha256:2159a11e112eb3336fdd5e390e4d72161d31d14b46686936a44d719d4ec9d906

# if you need a quicker turnaround, you can patch the image like the below,
# before the automated image build picks up the new CVE fixes (24-48 hours, usually)

# USER root
# RUN apk update && \
# apk add --upgrade --no-cache libssl3 libcrypto3

USER nonroot
