---
name: Dependabot Auto-Merge

on:
  workflow_run:
    workflows: ["Publish Base Docker images"]
    types: [completed]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' &&
      (github.event_name == 'pull_request_target' ||
       (github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success'))
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: >-
            ${{ github.event.pull_request.html_url ||
            github.event.workflow_run.pull_requests[0].html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
