# /Users/matts/work/Aquia/repos/base-docker-images/.github/workflows/publish-base-images.yml
name: Publish Base Docker images

on:
  push:
    tags:
      - "release/**"
    branches:
      - main
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  # Use a default tag for PRs to allow parsing logic to run without error
  # For other events (main push, tag push), use the actual ref
  TAG: ${{ (github.event_name == 'pull_request' && 'release/python-base/v0.0.0-pr') || github.ref }}

jobs:
  publish_image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]
    permissions:
      contents: write # Needed for checkout, potentially release creation if done here
      packages: write # Needed to push to GHCR
      security-events: write # Needed for Trivy SARIF upload
      actions: read # Needed for cache actions? (Often implicitly granted)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trivy - configure cache
        id: cache-trivy-db
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db-${{ matrix.platform }}
          restore-keys: |
            ${{ runner.os }}-trivy-db-${{ matrix.platform }}
            ${{ runner.os }}-trivy-db-

      - name: Sanitize platform name for tag/name suffix
        id: sanitize_platform
        run: echo "suffix=$(echo ${{ matrix.platform }} | tr '/' '-')" >> $GITHUB_OUTPUT

      - name: Extract Image Base Name and Version from Tag
        id: parse_tag
        run: |
          # Use grep -oP for Perl-compatible regex to extract parts, sed to remove prefix
          match=$(echo "${{ env.TAG }}" | grep -oP 'release/([^/]+)/v(\d+\.\d+\.\d+(-[a-zA-Z0-9.-]+)?)' | sed 's/release\///')
          echo "Input TAG: ${{ env.TAG }}"
          echo "Regex match result: $match"
          if [[ $match =~ ^([^/]+)/v(.+)$ ]]; then
              echo "Match found (Release Tag format)"
              image_base_name="${BASH_REMATCH[1]}"
              version="${BASH_REMATCH[2]}" # Includes potential pre-release identifiers like -pr
              echo "image_base_name=$image_base_name" >> $GITHUB_OUTPUT
              echo "version=$version" >> $GITHUB_OUTPUT
              echo "Parsed: image_base_name=$image_base_name, version=$version"
          else
              # Not a release tag - likely main branch push or PR default
              echo "Not a release tag build (TAG='${{ env.TAG }}'). Setting default values for test build."
              # Use 'python-base' as default, similar to PR logic, so test build can find Dockerfile
              default_image="python-base"
              default_version="dev" # Use 'dev' for non-release builds
              echo "image_base_name=$default_image" >> $GITHUB_OUTPUT
              echo "version=$default_version" >> $GITHUB_OUTPUT
              echo "Using defaults: image_base_name=$default_image, version=$default_version"
          fi

      - name: Construct Platform-Specific Image Name
        id: image_name
        run: |
          platform_image_name="${{ steps.parse_tag.outputs.image_base_name }}-${{ steps.sanitize_platform.outputs.suffix }}"
          echo "platform_image_name=${platform_image_name}" >> $GITHUB_OUTPUT
          echo "Platform Image Name: ${platform_image_name}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image for ${{ matrix.platform }} (Test)
        id: build_test
        uses: docker/build-push-action@v6
        with:
          pull: true
          file: Dockerfile.${{ steps.parse_tag.outputs.image_base_name }}
          platforms: ${{ matrix.platform }}
          load: true # Load the image into docker daemon for testing/scanning
          tags: ${{ github.repository }}/${{ steps.image_name.outputs.platform_image_name }}:test
          cache-from: type=gha,scope=${{ github.repository }}-${{ steps.image_name.outputs.platform_image_name }}
          cache-to: type=gha,mode=max,scope=${{ github.repository }}-${{ steps.image_name.outputs.platform_image_name }}

      - name: Run Trivy vulnerability scanner for ${{ matrix.platform }}
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ github.repository }}/${{ steps.image_name.outputs.platform_image_name }}:test
          format: "sarif"
          output: "trivy-results-${{ steps.sanitize_platform.outputs.suffix }}.sarif"
          exit-code: "1" # Fail the build if vulnerabilities are found (respecting severity/ignore-unfixed)
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH,MEDIUM" # Scan for Medium and above

      - name: Get installed package versions for ${{ matrix.platform }}
        id: get_versions
        run: |
            image_base_name="${{ steps.parse_tag.outputs.image_base_name }}"
            platform_image_name="${{ steps.image_name.outputs.platform_image_name }}"
            test_tag="${{ github.repository }}/${platform_image_name}:test"
            output_file=".env.versions.${{ steps.sanitize_platform.outputs.suffix }}"
            echo "Output file: $output_file"
            echo "Test tag: $test_tag"
            extraction_status="false" # Default to false

            # Check if the image is one that should have a versions file
            if [[ "$image_base_name" == "python-base" || "$image_base_name" == "nodejs-base" || "$image_base_name" == "openjdk17-base" ]]; then
                echo "Attempting to extract versions from $test_tag for $platform_image_name"
                # Attempt extraction. Use 'sh -c' to better control exit code based on 'cat' success.
                if docker run --rm --platform ${{ matrix.platform }} "$test_tag" sh -c 'cat /tmp/versions.txt && exit 0 || exit 1' > "$output_file"; then
                    # Check if the created file actually has content
                    if [ -s "$output_file" ]; then
                        echo "Versions extracted successfully to $output_file"
                        extraction_status="true"
                    else
                        echo "Warning: Command succeeded but extracted versions file '$output_file' is empty. Treating as failure."
                        # Keep extraction_status="false"
                        rm -f "$output_file" # Remove empty file
                    fi
                else
                    echo "Warning: Failed to execute 'cat /tmp/versions.txt' in container $test_tag. Exit code: $?"
                    # Ensure the potentially partially created/empty file is removed on error
                    rm -f "$output_file"
                    # Keep extraction_status="false"
                fi
            else
                echo "No version extraction needed for $platform_image_name."
                # Keep extraction_status="false"
            fi

            # Set outputs
            echo "extraction_success=$extraction_status" >> $GITHUB_OUTPUT
            # Set path only if extraction was truly successful and file should exist
            if [[ "$extraction_status" == "true" ]]; then
              echo "output_file_path=$output_file" >> $GITHUB_OUTPUT
            else
              echo "output_file_path=" >> $GITHUB_OUTPUT
            fi
            pwd
            ls -al

      - name: Upload versions artifact (from amd64)
        uses: actions/upload-artifact@v3
        # Only upload if extraction succeeded on the amd64 platform
        if: matrix.platform == 'linux/amd64' && steps.get_versions.outputs.extraction_success == 'true'
        with:
          name: versions-file-amd64
          path: .env.versions.linux-amd64
          retention-days: 1
          if-no-files-found: warn

      - name: Check if .env.versions file exists (Local check before dotenv)
        id: check_env_file
        run: |
          if [ -f ".env.versions.${{ steps.sanitize_platform.outputs.suffix }}" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Does not exist"
            exit 1
          fi
      - name: Rename versions file to .env (Local Env)
        if: steps.check_env_file.outputs.exists == 'true'
        run: mv .env.versions.${{ steps.sanitize_platform.outputs.suffix }} .env

      - name: Read package versions for ${{ matrix.platform }} (Local Env)
        if: steps.check_env_file.outputs.exists == 'true'
        id: dotenv_local
        uses: xom9ikk/dotenv@v2.3.0
        with:
          path: . # Read the renamed .env file in the current directory

      # --- Metadata for Final Push ---
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ steps.image_name.outputs.platform_image_name }}
          tags: |
            # Add SemVer tag for release pushes (e.g., v1.2.3)
            type=semver,pattern={{version}},value=${{ steps.parse_tag.outputs.version }},enable=${{ github.event_name == 'push' && github.ref_type == 'tag' }}
            # Add latest tag for release pushes
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref_type == 'tag' }} # <-- ADDED THIS LINE
            # Add dev tag for non-release pushes/PRs (e.g., dev-a1b2c3d)
            type=raw,value=dev-${{ github.sha }},enable=${{ github.event_name != 'push' || github.ref_type != 'tag' }}
          labels: |
            org.opencontainers.image.title=${{ steps.image_name.outputs.platform_image_name }} (${{ matrix.platform }})
            org.opencontainers.image.description=Base image for ${{ steps.parse_tag.outputs.image_base_name }} targeting ${{ matrix.platform }}
            org.opencontainers.image.vendor=Aquia Inc
            org.opencontainers.image.build-url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            org.opencontainers.image.architecture=${{ matrix.platform }} # Use matrix platform directly

      - name: Build and push Docker image for ${{ matrix.platform }}
        id: docker_build
        uses: docker/build-push-action@v6
        # Only push if it's a push event to a tag (i.e., a release)
        if: github.event_name == 'push' && github.ref_type == 'tag'
        with:
          pull: true 
          file: Dockerfile.${{ steps.parse_tag.outputs.image_base_name }}
          push: true 
          platforms: ${{ matrix.platform }} 
          # Use tags and labels generated by the metadata action
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.repository }}-${{ steps.image_name.outputs.platform_image_name }}
          cache-to: type=gha,mode=max,scope=${{ github.repository }}-${{ steps.image_name.outputs.platform_image_name }}

      - name: Output SHA256 digest for ${{ matrix.platform }}
        # Only show digest if the image was pushed
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: |
          echo "SHA256 digest for ${{ steps.image_name.outputs.platform_image_name }}: ${{ steps.docker_build.outputs.digest }}"
          ls -al 

  create_release:
    runs-on: ubuntu-latest
    needs: publish_image 
    # Run only if the trigger was a push to a tag AND the publish_image job succeeded
    if: github.event_name == 'push' && github.ref_type == 'tag' && needs.publish_image.result == 'success'
    permissions:
      contents: write # Needed to create the GitHub Release
      actions: read # Needed to download artifacts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Image Base Name and Version from Tag for Release
        id: parse_tag_release
        run: |
          tag_ref="${{ github.ref }}" # e.g., refs/tags/release/python-base/v1.0.0
          # Regex to capture base name and version from the specific release tag format
          if [[ $tag_ref =~ refs/tags/release/([^/]+)/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
              image_base_name="${BASH_REMATCH[1]}"
              version="${BASH_REMATCH[2]}"
              echo "Parsed from release tag: image_base_name=$image_base_name, version=$version"
              echo "image_base_name=$image_base_name" >> $GITHUB_OUTPUT
              echo "version=$version" >> $GITHUB_OUTPUT
          else
              echo "Error: Could not parse release tag format from ref: $tag_ref"
              echo "Expected format: refs/tags/release/<image-name>/vX.Y.Z"
              exit 1
          fi

      - name: Download versions artifact
        id: download_artifact
        # Only attempt download if the image base name is one expected to have versions
        if: |
          steps.parse_tag_release.outputs.image_base_name == 'python-base' ||
          steps.parse_tag_release.outputs.image_base_name == 'nodejs-base' ||
          steps.parse_tag_release.outputs.image_base_name == 'openjdk17-base'
        uses: actions/download-artifact@v4
        with:
          name: versions-file-amd64 
          path: . 

      - name: Rename downloaded artifact to .env
        # Only run if the download step succeeded (outcome is 'success')
        if: steps.download_artifact.outcome == 'success'
        run: |
          if [ -f ".env.versions.linux-amd64" ]; then
            cp .env.versions.linux-amd64 .env
            echo "Renamed .env.versions.linux-amd64 to .env"
          else
            echo "Warning: Expected file .env.versions.linux-amd64 not found after download."
            # Decide if this should be an error - exit 1?
          fi

      - name: Read downloaded package versions
        id: dotenv_release
        # Only run if the download step succeeded (implies rename also attempted/succeeded)
        if: steps.download_artifact.outcome == 'success'
        uses: xom9ikk/dotenv@v2.3.0
        with:
          path: . # Read the .env file in the current directory

      - name: Create GitHub Release Body
        id: release_body
        run: |
          image_base_name="${{ steps.parse_tag_release.outputs.image_base_name }}"
          version_tag="${{ steps.parse_tag_release.outputs.version }}"
          repo_name="${{ github.repository }}"
          registry="${{ env.REGISTRY }}"

          # Start with the base body
          body=$(cat <<EOF
          Platform-specific Docker images for \`$image_base_name\` version \`$version_tag\` pushed.

          The \`latest\` tag for each platform now points to this release.

          **Published Images & Tags:**

          *   **linux/amd64:**
              *   Image: \`$registry/$repo_name/$image_base_name-linux-amd64\`
              *   Tag: \`$version_tag\`
              *   Tag: \`latest\`
          *   **linux/arm64:**
              *   Image: \`$registry/$repo_name/$image_base_name-linux-arm64\`
              *   Tag: \`$version_tag\`
              *   Tag: \`latest\`
          EOF
          )

          # Conditionally add specific version tags if dotenv step succeeded
          # Check outcome of the dotenv step itself
          if [[ "${{ steps.dotenv_release.outcome }}" == "success" ]]; then
            specific_tags_section=""
            if [[ "$image_base_name" == "python-base" ]]; then
              # Use shell variable syntax to access vars set by dotenv
              py_major="$python_major_tag"
              py_minor="$python_minor_tag"
              # Check if variables were actually loaded
              if [ -n "$py_major" ] && [ -n "$py_minor" ]; then
                specific_tags_section=$(cat <<EOF

          **Python Version Tags:**
          *   Major: \`${py_major}\`
          *   Minor: \`${py_minor}\`
          EOF
                )
              else
                echo "Warning: Python tags (python_major_tag, python_minor_tag) not found in environment variables from .env file."
              fi
            elif [[ "$image_base_name" == "nodejs-base" ]]; then
              # Use shell variable syntax
              node_major="$nodejs_major_tag"
              node_minor="$nodejs_minor_tag"
              if [ -n "$node_major" ] && [ -n "$node_minor" ]; then
                specific_tags_section=$(cat <<EOF

          **Node.js Version Tags:**
          *   Major: \`${node_major}\`
          *   Minor: \`${node_minor}\`
          EOF
                )
              else
                echo "Warning: Node.js tags (nodejs_major_tag, nodejs_minor_tag) not found in environment variables from .env file."
              fi
            elif [[ "$image_base_name" == "openjdk17-base" ]]; then
              # Use shell variable syntax
              jdk_major="$openjdk_major_tag"
              jdk_minor="$openjdk_minor_tag"
              if [ -n "$jdk_major" ] && [ -n "$jdk_minor" ]; then
                specific_tags_section=$(cat <<EOF

          **OpenJDK Version Tags:**
          *   Major: \`${jdk_major}\`
          *   Minor: \`${jdk_minor}\`
          EOF
                )
              else
                echo "Warning: OpenJDK tags (openjdk_major_tag, openjdk_minor_tag) not found in environment variables from .env file."
              fi
            fi
            # Append the specific tags section if it was generated
            body="${body}${specific_tags_section}"
          else
             # Log if dotenv step didn't succeed (e.g., artifact download failed)
             echo "Skipping specific version tags because dotenv step outcome was not success: (${{ steps.dotenv_release.outcome }})"
          fi

          # Add pull examples
          pull_examples=$(cat <<EOF

          **Pull Examples:**

          *   **AMD64 / x86_64 (Version Specific):**
              \`\`\`bash
              docker pull $registry/$repo_name/${image_base_name}-linux-amd64:$version_tag
              \`\`\`
          *   **AMD64 / x86_64 (Latest):**
              \`\`\`bash
              docker pull $registry/$repo_name/${image_base_name}-linux-amd64:latest
              \`\`\`
          *   **ARM64 / aarch64 (Version Specific):**
              \`\`\`bash
              docker pull $registry/$repo_name/${image_base_name}-linux-arm64:$version_tag
              \`\`\`
          *   **ARM64 / aarch64 (Latest):**
              \`\`\`bash
              docker pull $registry/$repo_name/${image_base_name}-linux-arm64:latest
              \`\`\`
          EOF
          )
          # Append pull examples
          body="${body}${pull_examples}"

          # escape special chars for JSON output
          echo "BODY_TEXT<<EOF" >> $GITHUB_ENV
          echo "$body" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          # read it back escaped and set the output
          echo "body=$(python -c 'import json, os; print(json.dumps(os.environ["BODY_TEXT"]))')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} # Use the tag that triggered the workflow (e.g., release/python-base/v1.0.0)
          # Construct a meaningful release name
          name: "Release ${{ steps.parse_tag_release.outputs.image_base_name }} v${{ steps.parse_tag_release.outputs.version }}"
          body: ${{ steps.release_body.outputs.body }} # Use the JSON-escaped body from the previous step
          draft: false
          prerelease: false # Mark as a full release
        env:
          # GITHUB_TOKEN is automatically available to the action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
